copyright: Kirill Solovei &copy; 2023-2024

extra:
  analytics:
    provider: google
    property: G-E9FSFDM6ER
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hatedabamboo/
    - icon: fontawesome/brands/github
      link: https://github.com/hatedabamboo/
    - icon: fontawesome/brands/telegram
      link: https://t.me/hatedabamboo/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hatedabamboo/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hatedabamboo/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@hatedabamboo

markdown_extensions: 
  - admonition
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - blog:
      archive: true
      archive_date_format: YYYY
      blog_dir: .
      pagination: true
      pagination_per_page: 10
      post_date_format: long
      post_dir: posts
      post_excerpt: required
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md

site_name: hatedabamboo notes
site_url: https://notes.hatedabamboo.me

theme:
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
  font:
    text: Open Sans
  icon:
    logo: material/note-edit-outline
    next: fontawesome/solid/angle-right
    previous: fontawesome/solid/angle-left
    top: fontawesome/solid/angle-up
  name: material
  palette:
    primary: white
    accent: light blue
