title: hatedabamboo notes
email: hatedabamboo@pm.me
description: >-
  Notes about personal and professional experience in DevOps, Systems Engineering and AWS.
domain: hatedabamboo.github.io
baseurl: "notes"
url: "hatedabamboo.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/hatedabamboo" }
    - { platform: twitter, user_url: "https://linkedin.com/hatedabamboo" }
    - { platform: telegram, user_url: "https://t.me/hatedabamboo" }
